"""Create tasks table and update relationships

Revision ID: 3236f48525f6
Revises: 8b998e42649b
Create Date: 2024-06-30 08:57:14.276856

"""

from collections.abc import Sequence

import advanced_alchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3236f48525f6"
down_revision: str | None = "8b998e42649b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tasks",
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("root_folder", sa.String(), nullable=False),
        sa.Column("creator_id", advanced_alchemy.types.GUID(length=16), nullable=False),
        sa.Column("id", advanced_alchemy.types.GUID(length=16), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.Column("created_at", advanced_alchemy.types.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", advanced_alchemy.types.DateTimeUTC(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["creator_id"],
            ["users.id"],
            name=op.f("fk_tasks_creator_id_users"),
            ondelete="set null",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tasks")),
        comment="Tasks for annotating data",
    )
    op.create_table(
        "user_tasks",
        sa.Column("user_id", advanced_alchemy.types.GUID(length=16), nullable=False),
        sa.Column("task_id", advanced_alchemy.types.GUID(length=16), nullable=False),
        sa.ForeignKeyConstraint(
            ["task_id"], ["tasks.id"], name=op.f("fk_user_tasks_task_id_tasks")
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_user_tasks_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", "task_id", name=op.f("pk_user_tasks")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_tasks")
    op.drop_table("tasks")
    # ### end Alembic commands ###
