"""create users

Revision ID: 8b998e42649b
Revises:
Create Date: 2024-06-30 07:34:31.776150

"""

from collections.abc import Sequence

import advanced_alchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b998e42649b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("username", sa.String(), unique=True, nullable=False),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("annotation_rate", sa.Float(), default=0.0, nullable=False),
        sa.Column("id", advanced_alchemy.types.GUID(length=16), nullable=False),
        sa.Column("created_at", advanced_alchemy.types.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("updated_at", advanced_alchemy.types.DateTimeUTC(timezone=True), nullable=False),
        sa.Column("sa_orm_sentinel", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        comment="Users table",
    )


def downgrade() -> None:
    op.drop_table("users")
